topology:
  # 3 DUTs - 2 linecards (dut 0, 1) and 1 Supervisor card (dut 2). Each linecard has 2 asics - asic0 and asic1
  #
  #  - asic0 on linecard dut0 connected to 2 T3 VMs - one on 2 port lag and one on a single routed port
  #  - asic1 on linecard dut0 connected to 2 T3 VMs - one on 2 port lag and one on a single routed port
  #  - asic0 on linecard dut1 connected to 2 T1 VMs- one on 2 port lag and one on a single routed port
  #  - asic1 on linecard dut1 connected to 2 T1 VMs - one on 2 port lag and one on a single routed port
  #
  # ptf ports are numbered 0-11

  dut_num: 3
  VMs:
    ARISTA11T3:
      vlans:
        - "0.4@12"
        - "0.5@13"
      vm_offset: 0
    ARISTA13T3:
      vlans:
        - "0.8@14"
      vm_offset: 1
    ARISTA14T3:
      vlans:
        - "0.26@15"
        - "0.27@16"
      vm_offset: 2
    ARISTA16T3:
      vlans:
        - "0.23@17"
      vm_offset: 3
    ARISTA11T1:
      vlans:
        - "1.2@18"
        - "1.3@19"
      vm_offset: 4
    ARISTA13T1:
      vlans:
        - "1.6@20"
      vm_offset: 5
    ARISTA14T1:
      vlans:
         - "1.14@21"
         - "1.15@22"
      vm_offset: 6
    ARISTA16T1:
      vlans:
        - "1.16@23"
      vm_offset: 7
  DUT:
    vs_chassis:
      inband_port:
        - [19, 40]
        - [19, 40]
      midplane_port:
        - 0
        - 0
        - 0
      midplane_address:
        - 10.7.1.100/16
        - 10.7.2.100/16
        - 10.7.0.100/16
      midplane_subnet: 10.7.0.0/16
      chassis_db_ip: 10.7.0.100
    loopback:
      ipv4:
        - 10.2.0.1/32
        - 10.2.0.2/32
      ipv6:
        - FC01:10::1/128
        - FC01:11::1/128

configuration_properties:
  common:
    podset_number: 400
    tor_number: 16
    tor_subnet_number: 8
    max_tor_subnet_number: 32
    tor_subnet_size: 128
    dut_asn: 65101
    dut_type: SpineRouter
    nhipv4: 10.20.246.254
    nhipv6: FC0B::FF
  core:
    swrole: core
  leaf:
    swrole: leaf

configuration:
  ARISTA11T3:
    properties:
      - common
      - core
    bgp:
      asn: 65201
      peers:
        65101:
          - 10.0.1.0
          - FC01::1
    interfaces:
      Loopback0:
        ipv4: 100.2.0.1/32
        ipv6: 2064:200::1/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.1.1/31
        ipv6: FC01::2/126
    bp_interface:
      ipv4: 10.20.246.1/24
      ipv6: fc0b::2/64

  ARISTA13T3:
    properties:
      - common
      - core
    bgp:
      asn: 65201
      peers:
        65101:
          - 10.0.1.4
          - FC01::9
        65100:
          - 10.0.0.25
          - FC00::4d
    interfaces:
      Loopback0:
        ipv4: 100.2.0.3/32
        ipv6: 2064:200::3/128
      Ethernet1:
        ipv4: 10.0.1.5/31
        ipv6: FC01::a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.20.246.3/24
      ipv6: fc0b::6/64

  ARISTA14T3:
    properties:
      - common
      - core
    bgp:
      asn: 65201
      peers:
        65101:
          - 10.0.1.6
          - FC01::d
    interfaces:
      Loopback0:
        ipv4: 100.2.0.4/32
        ipv6: 2064:200::4/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.1.7/31
        ipv6: FC01::e/126
    bp_interface:
      ipv4: 10.20.246.4/24
      ipv6: fc0b::9/64

  ARISTA16T3:
    properties:
      - common
      - core
    bgp:
      asn: 65201
      peers:
        65101:
          - 10.0.1.10
          - FC01::15
    interfaces:
      Loopback0:
        ipv4: 100.2.0.6/32
        ipv6: 2064:200::6/128
      Ethernet1:
        ipv4: 10.0.1.11/31
        ipv6: FC01::16/126
        dut_index: 0
    bp_interface:
      ipv4: 10.20.246.6/24
      ipv6: fc0b::d/64

  ARISTA11T1:
    properties:
      - common
      - leaf
    bgp:
      asn: 65010
      peers:
        65101:
          - 10.0.1.12
          - FC01::19
    interfaces:
      Loopback0:
        ipv4: 100.2.0.7/32
        ipv6: 2064:200::7/128
      Ethernet1:
        lacp: 1
        dut_index: 1
      Ethernet2:
        lacp: 1
        dut_index: 1
      Port-Channel1:
        ipv4: 10.0.1.13/31
        ipv6: FC01::1a/126
    bp_interface:
      ipv4: 10.20.246.7/24
      ipv6: fc0b::e/64
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700
  ARISTA13T1:
    properties:
      - common
      - leaf
    bgp:
      asn: 65011
      peers:
        65101:
          - 10.0.1.16
          - FC01::21
    interfaces:
      Loopback0:
        ipv4: 100.2.0.9/32
        ipv6: 2064:200::9/128
      Ethernet1:
        ipv4: 10.0.1.17/31
        ipv6: FC01::22/126
        dut_index: 1
    bp_interface:
      ipv4: 10.20.246.9/24
      ipv6: fc0b::12/64
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700
  ARISTA14T1:
    properties:
      - common
      - leaf
    bgp:
      asn: 65012
      peers:
        65101:
          - 10.0.1.18
          - FC01::25
    interfaces:
      Loopback0:
        ipv4: 100.2.0.10/32
        ipv6: 2064:200::a/128
      Ethernet1:
        lacp: 1
        dut_index: 1
      Ethernet2:
        lacp: 1
        dut_index: 1
      Port-Channel1:
        ipv4: 10.0.1.19/31
        ipv6: FC01::26/126
    bp_interface:
      ipv4: 10.20.246.10/24
      ipv6: fc0b::15/64
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700
  ARISTA16T1:
    properties:
      - common
      - leaf
    bgp:
      asn: 65013
      peers:
        65101:
          - 10.0.1.22
          - FC01::2d
    interfaces:
      Loopback0:
        ipv4: 100.2.0.12/32
        ipv6: 2064:200::c/128
      Ethernet1:
        ipv4: 10.0.1.23/31
        ipv6: FC01::2e/126
        dut_index: 1
    bp_interface:
      ipv4: 10.20.246.12/24
      ipv6: fc0b::19/64
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700
